### ISSUE TITLE
No reduction when interestingness test always succeeds

### ISSUE THREAD

**Issue by langston-barrett** [langston-barrett/treereduce#33]
There's a bug where `treereduce` won't reduce a program if the interestingness check always succeeds:
```sh
treereduce-c --no-verify --jobs 24 --output bench.c -s crates/treereduce/benches/c/basic.c --stats -v -- /nix/store/i9q0jv6qnvg7zal98rqi7aq31k3p89hw-coreutils-9.0/bin/true |& grep -v Idling
```

**Comment by pacak** [comment]
FWIW I'm still getting it stuck idling after making some progress

[DEBUG] Idling 18446744073709551608 / 32... idle=18446744073709551608 threads=32

**Comment by langston-barrett** [comment]
@pacak I'm sorry to hear it! Can you post a new issue with a reproducer?

**Comment by pacak** [comment]
At the moment it's basically on any project. Maybe I'm doing something wrong.

```
% treereduce-rust  -s foo.rs --interesting-exit-code 1 -- rustc @@
[INFO] Starting pass 1 / 2
[INFO] Original size: 20
[INFO] Reduced to size: 0 id=1 kind="delete" priority=20 size=0
^C
% cat foo.rs
fn main() {
    1
}
```
