### ISSUE TITLE
hang?

### ISSUE THREAD

**Issue by matthiaskrgr** [langston-barrett/treereduce#74]
I came across this file

````rust
#![feature(type_alias_impl_trait)]

#[derive(Clone)]
struct CopyIfEq<T, U>(T, U);

impl<T: Copy> Copy for CopyIfEq<T, T> {}

type E<'a, 'b> = impl Sized;

fn foo<'a: 'b, 'b, 'c>(x: &'static i32, mut y: &'a i32) -> E<'b, 'c> {
    let v = CopyIfEq::<*mut _, *mut _>(&mut { x }, &mut y);

    // This assignment requires that `x` and `y` have the same type due to the
    // `Copy` impl. The reason why we are using a copy to create a constraint
    // is that only borrow checking (not regionck in type checking) enforces
    // this bound.
    let u = v;
    let _: *mut &'a i32 = u.1;
    unsafe {
        let _: &'b i32 = *u.0;
    }
    u.0
    //~^ ERROR hidden type for `E<'b, 'c>` captures lifetime that does not appear in bounds
}

fn CopyIfEq() {}
````

where treereduce seems to not output anything at all.
Is this some kind of parsing error of the file that messes things up?

**Comment by langston-barrett** [comment]
@matthiaskrgr Thanks for the report! Can you share the full command line you used, and which revision of treereduce you're using?

**Comment by matthiaskrgr** [comment]
oh, sorry :sweat: 

So the command I used was `treereduce-rust --passes 10 --min-reduction 10 --interesting-stderr="panic" unred.rs -- ~/.rustup/toolchains/local-debug-assertions/bin/rustc --crate-type lib @@.rs`  (the ice requires debug assertions) but a vanilla nightly rustc also hangs.

treereduce 0.2.2

**Comment by langston-barrett** [comment]
> OOOH I think I just forgot to put --source before $file.rs? :(

Yeah, that sounds correct. `treereduce` is set up to take input on stdin as well, so it's likely just waiting to read. You can see similar behaviors in other programs such as `cat` or `jq`.

**Comment by langston-barrett** [comment]
Closing for now, as this is expected behavior.
